[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  VITE_API_URL = "https://qualycorpore.chztech.com.br/api"

# Redirecionamento específico para agendamento público
[[redirects]]
  from = "/agendamento/*"
  to = "/index.html"
  status = 200
  force = true

# Redirecionamento geral para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"

# Headers específicos para agendamento
[[headers]]
  for = "/agendamento/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
  




